SalesManagement/Controllers/GEController.cs
using log4net;
using SalesManagement.DataControllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SalesManagement.Hubs;

namespace SalesManagement.Controllers
{
    [Authorize]
    public class GEController : Controller
    {
        private static readonly ILog Logger = LogManager.GetLogger(typeof(GEController));

        public ActionResult Index() => View();

        public PartialViewResult GetAllGE()
        {
            using (var ctx = new CapData())
            {
                var result = ctx.DATA_CORRESPONDANCES_CAP_ETAB_GROUPES.ToList();
                List<GE> listGE = new List<GE>();
                int x ,y = 0;
                        
                foreach (var corresp in result)
                {
                    x = y * 100 / result.Count;

                    ProgressHub.SendMessage($"Chargement des données {x} %", x);
                    GE ge = new GE
                    {
                        Etb_name = corresp.CAP_ETAB.ETB_NAME,
                        Siret = corresp.CAP_ETAB.ETB_SIRET != null ? corresp.CAP_ETAB.ETB_SIRET : "Non renseigné",
                        LibelleGroupe = corresp.DATA_GROUPES.LIBELLE,
                        LibelleSegment = corresp.DATA_GROUPES.DATA_SEGMENTS.LIBELLE,
                        NomPrenomCom = GetCom(corresp.IDGROUPE) != "" ? GetCom(corresp.IDGROUPE) : "Non renseigné"
                    };
                    listGE.Add(ge);
                    y++;
                }
                
                return PartialView("Partial/_Export", listGE);
            }
        }
        public PartialViewResult GetGE(string libelle, int page, int pageSize)
        {
            using(CapData ctx = new CapData())
            {
                int v, y = 0;

                var result = new List<DATA_CORRESPONDANCES_CAP_ETAB_GROUPES>();

                int skip = (page - 1) * pageSize;

                if (libelle == "")
                    result = ctx.DATA_CORRESPONDANCES_CAP_ETAB_GROUPES.ToList();
                else
                    result = ctx.DATA_CORRESPONDANCES_CAP_ETAB_GROUPES.Where(x => x.CAP_ETAB.ETB_NAME.Contains(libelle) || x.CAP_ETAB.ETB_SIRET.Contains(libelle) || x.DATA_GROUPES.LIBELLE.Contains(libelle) || x.DATA_GROUPES.LIBELLE == libelle).OrderBy(x => x.IDCORRESPONDANCE).ToList();

                Pagination p = new Pagination
                {
                    Page = page,
                    Libelle = libelle,
                    PageSize = pageSize,
                    PageCount = (int)Math.Ceiling((double)result.Count / pageSize),
                    ResearchType = "Libelle",
                    TotalResultCout = result.ToList().Count
                };
                if (libelle == "")
                    result = result.Skip(skip).Take(pageSize).ToList();


                foreach (var corresp in result)
                {
                    v = y * 100 / result.Count;
                    ProgressHub.SendMessage($"Chargement des données {v} %", v);

                    GE ge = new GE
                    {
                        Etb_id = corresp.ETB_ID,
                        Etb_name = corresp.CAP_ETAB.ETB_NAME,
                        Siret = corresp.CAP_ETAB.ETB_SIRET != null ? corresp.CAP_ETAB.ETB_SIRET : "Non renseigné",
                        IdGroupe = corresp.DATA_GROUPES.IDGROUPE,
                        LibelleGroupe = corresp.DATA_GROUPES.LIBELLE,
                        LibelleRegion = corresp.DATA_GROUPES.DATA_REGIONS.REGION,
                        LibelleSecteur = corresp.DATA_GROUPES.DATA_SECTEURS.LIBELLE,
                        LibelleTaille = corresp.DATA_GROUPES.DATA_TAILLES.LIBELLE,
                        LibelleSegment = corresp.DATA_GROUPES.DATA_SEGMENTS.LIBELLE,
                        NomPrenomCom = GetCom(corresp.IDGROUPE) != "" ? GetCom(corresp.IDGROUPE) : "Non renseigné",
                        Etb_adr = GetAdr(corresp.ETB_ID, 1) != null ? GetAdr(corresp.ETB_ID, 1) : "Non renseigné",
                        Etb_adr2 = GetAdr(corresp.ETB_ID, 2) != null ? GetAdr(corresp.ETB_ID, 2) : "Non renseigné",
                        Etb_adr3 = GetAdr(corresp.ETB_ID, 3) != null ? GetAdr(corresp.ETB_ID, 3) : "Non renseigné",
                        Etb_ville = corresp.CAP_ETAB.CAP_ADRESSE.ADR_VILLE,
                        Etb_naf = corresp.CAP_ETAB.CAP_NAF.NAF_CODE,
                        Date_AddEtb = corresp.CAP_ETAB.FLAG_DATADD.HasValue ? corresp.CAP_ETAB.FLAG_DATADD.Value.ToShortDateString() : "Non renseigné",
                        Date_AddGrp = corresp.DATA_GROUPES.DATE_ADD.HasValue ? corresp.DATA_GROUPES.DATE_ADD.Value.ToShortDateString() : "Non renseigné",
                        Date_AddEtbGrp = corresp.DATE_ADD.HasValue ? corresp.DATE_ADD.Value.ToShortDateString() : "Non renseigné"
                    };
                    p.GE.Add(ge);
                    y++;
                }

                return PartialView("Partial/_GE_PartialView", p);
            }
          
        }
        public PartialViewResult GetGEByDate(DateTime startDate, DateTime endDate, int page, int pageSize)
        {
            using (CapData ctx = new CapData())
            {
                int v, y = 0;
                var result = new List<DATA_CORRESPONDANCES_CAP_ETAB_GROUPES>();

                int skip = (page - 1) * pageSize;

                result = ctx.DATA_CORRESPONDANCES_CAP_ETAB_GROUPES.SqlQuery("SELECT * FROM DATA_CORRESPONDANCES_CAP_ETAB_GROUPES WHERE CONVERT(date, DATE_ADD) BETWEEN '" + startDate.ToString("yyyy-MM-dd") + "' AND '" + endDate.ToString("yyyy-MM-dd") + "' ").OrderBy(x => x.IDCORRESPONDANCE).ToList();

                Pagination p = new Pagination
                {
                    Page = page,
                    Libelle = startDate.ToShortDateString() + "," + endDate.ToShortDateString(),
                    PageSize = pageSize,
                    PageCount = (int)Math.Ceiling((double)result.Count / pageSize),
                    ResearchType = "Date"
                };

                foreach (var corresp in result.Skip(skip).Take(pageSize))
                {
                    v = y * 100 / result.Count;
                    ProgressHub.SendMessage($"Chargement des données {v} %", v);

                    GE ge = new GE
                    {
                        Etb_id = corresp.ETB_ID,
                        Etb_name = corresp.CAP_ETAB.ETB_NAME,
                        Siret = corresp.CAP_ETAB.ETB_SIRET != null ? corresp.CAP_ETAB.ETB_SIRET : "Non renseigné",
                        IdGroupe = corresp.DATA_GROUPES.IDGROUPE,
                        LibelleGroupe = corresp.DATA_GROUPES.LIBELLE,
                        LibelleRegion = corresp.DATA_GROUPES.DATA_REGIONS.REGION,
                        LibelleSecteur = corresp.DATA_GROUPES.DATA_SECTEURS.LIBELLE,
                        LibelleTaille = corresp.DATA_GROUPES.DATA_TAILLES.LIBELLE,
                        LibelleSegment = corresp.DATA_GROUPES.DATA_SEGMENTS.LIBELLE,
                        NomPrenomCom = GetCom(corresp.IDGROUPE) != "" ? GetCom(corresp.IDGROUPE) : "Non renseigné",
                        Etb_adr = GetAdr(corresp.ETB_ID, 1) != null ? GetAdr(corresp.ETB_ID, 1) : "Non renseigné",
                        Etb_adr2 = GetAdr(corresp.ETB_ID, 2) != null ? GetAdr(corresp.ETB_ID, 2) : "Non renseigné",
                        Etb_adr3 = GetAdr(corresp.ETB_ID, 3) != null ? GetAdr(corresp.ETB_ID, 3) : "Non renseigné",
                        Etb_ville = corresp.CAP_ETAB.CAP_ADRESSE.ADR_VILLE,
                        Etb_naf = corresp.CAP_ETAB.CAP_NAF.NAF_CODE,
                        Date_AddEtb = corresp.CAP_ETAB.FLAG_DATADD.HasValue ? corresp.CAP_ETAB.FLAG_DATADD.Value.ToShortDateString() : "Non renseigné",
                        Date_AddGrp = corresp.DATA_GROUPES.DATE_ADD.HasValue  ? corresp.DATA_GROUPES.DATE_ADD.Value.ToShortDateString() : "Non renseigné",
                        Date_AddEtbGrp = corresp.DATE_ADD.HasValue ? corresp.DATE_ADD.Value.ToShortDateString() : "Non renseigné"
                    };
                    p.GE.Add(ge);
                    y++;
                }
                p.TotalResultCout = result.ToList().Count;

                return PartialView("Partial/_GE_PartialView", p);
            }
        }
        public PartialViewResult GetListGroup()
        {
            using(CapData ctx =new CapData())
            {
                return PartialView("_SelectGroup_PartialView",ctx.DATA_GROUPES.ToList());
            }
        }
            
        public void AddCorrespondanceEG(int ETB_ID, int idGroup)
        {
            using (CapData ctx = new CapData())
            {
                var etb = ctx.CAP_ETAB.FirstOrDefault(x => x.ETB_ID == ETB_ID);
                var grp = ctx.DATA_GROUPES.FirstOrDefault(x => x.IDGROUPE == idGroup);

                var toInsert = new DATA_CORRESPONDANCES_CAP_ETAB_GROUPES
                {
                    IDGROUPE = idGroup,
                    ETB_ID = ETB_ID,
                    DATE_ADD = DateTime.Today
                };
                ctx.DATA_CORRESPONDANCES_CAP_ETAB_GROUPES.Add(toInsert);
                ctx.SaveChanges();

                Logger.Info($"Création de la correspondance etb-groupe {etb.ETB_NAME} - {grp.LIBELLE} | etb n° {ETB_ID} - idGroupe n° {idGroup}");
            }
        }
        public void DeleteCorrespondanceEG(int ETB_ID, int idGroup)
        {
            using (CapData ctx = new CapData())
            {
                var etb = ctx.CAP_ETAB.FirstOrDefault(x => x.ETB_ID == ETB_ID);
                var grp = ctx.DATA_GROUPES.FirstOrDefault(x => x.IDGROUPE == idGroup);

                var toDelete = ctx.DATA_CORRESPONDANCES_CAP_ETAB_GROUPES.FirstOrDefault(x => x.ETB_ID == ETB_ID && x.IDGROUPE == idGroup);

SalesManagement/Controllers/HelpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalesManagement.Controllers
{
    public class HelpController : Controller
    {
        [Authorize]
        public ActionResult Index() => View();
    }
}

SalesManagement/Controllers/SalesController.cs
using log4net;
using SalesManagement.DataControllers;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalesManagement.Controllers
{
    [Authorize]
    public class SalesController : Controller
    {
        private static readonly ILog Logger = LogManager.GetLogger(typeof(SalesController));

        public ActionResult Index() => View(GetComSegment());
        public PartialViewResult AddSale(string lastName, string firstName)
        {
            using (var ctx = new CapData())
            {
                var sale = new DATA_COMMERCIAUX
                {
                    NOM = lastName.ToUpper(),
                    PRENOM = firstName.ToUpper()
                };

                ctx.DATA_COMMERCIAUX.Add(sale);
                ctx.SaveChanges();

                Logger.Info($"Création du commercial {lastName} {firstName}");

                return PartialView("Partial/_SalesTable_PartialView", GetComSegment());
            }
        }
        public PartialViewResult EditSale(int id, string lastName, string firstName)
        {
            using (var ctx = new CapData())
            {
                var sale = ctx.DATA_COMMERCIAUX.FirstOrDefault(x => x.IDCOMMERCIAL == id);
                string oldLastName = sale.NOM;
                string oldfirstName = sale.PRENOM;

                sale.NOM = lastName.ToUpper();
                sale.PRENOM = firstName.ToUpper();

                ctx.SaveChanges();

                Logger.Info($"Modification du commercial {oldLastName} {oldfirstName} en {lastName} {firstName}");

                return PartialView("Partial/_SalesTable_PartialView", GetComSegment());
            }
        }
        public PartialViewResult DeleteSale(int id)
        {
            using (var ctx = new CapData())
            {
                var sale = ctx.DATA_COMMERCIAUX.FirstOrDefault(x => x.IDCOMMERCIAL == id);

                var saleGrp = ctx.DATA_CORRESPONDANCES_COMMERCIAUX_GROUPES_LEGALENTITY.Where(x => x.IDCOMMERCIAL == id).ToList();
                foreach (var corresp in saleGrp)
                {
                    ctx.DATA_CORRESPONDANCES_COMMERCIAUX_GROUPES_LEGALENTITY.Remove(corresp);
                }
                ctx.DATA_COMMERCIAUX.Remove(sale);
                ctx.SaveChanges();

                Logger.Info($"Suppression du commercial {sale.NOM} {sale.PRENOM}");

                return PartialView("Partial/_SalesTable_PartialView", GetComSegment());
            }
        }
        public int GetNbCorresp(int id)
        {
            using (var ctx = new CapData())
            {
                var nbCorresp = 0;
                nbCorresp = ctx.DATA_CORRESPONDANCES_COMMERCIAUX_GROUPES_LEGALENTITY.Where(x => x.IDCOMMERCIAL == id && x.IDLEGALENTITY == 1).Count();

                return nbCorresp;
            }
        }

        #region GetList
        public static List<ComSegment> GetComSegment()
        {
            using (var ctx = new CapData())
            {
                List<ComSegment> listComSegment = new List<ComSegment>();
                List<DATA_COMMERCIAUX> result = ctx.DATA_COMMERCIAUX.ToList();
                ComSegment c;
                string libelleSegment;

                foreach (var com in result)
                {
                    var listIdGroupe = ctx.DATA_CORRESPONDANCES_COMMERCIAUX_GROUPES_LEGALENTITY.Where(x => x.IDCOMMERCIAL == com.IDCOMMERCIAL).Select(x => x.IDGROUPE).ToList();
                    if (listIdGroupe.Count != 0)
                    {
                        var listIdSegment = ctx.DATA_GROUPES.Where(x => listIdGroupe.Contains(x.IDGROUPE)).Select(x => x.IDSEGMENT).ToList();
                        var communSegmentId = listIdSegment.GroupBy(x => x).OrderByDescending(g => g.Count()).SelectMany(g => g).First();
                        libelleSegment = ctx.DATA_SEGMENTS.FirstOrDefault(x => x.IDSEGMENT == communSegmentId).LIBELLE;
                    }
                    else
                        libelleSegment = "Non renseigné";

                    c = new ComSegment()
                    {
                        Com = com,
                        LibelleSegment = libelleSegment
                    };
                    listComSegment.Add(c);
                }
                return listComSegment;
            }
        }
        #endregion

    }
}

SalesManagement/Views/Shared/_InfosGroup_PartialView.cshtml
@model GeRSTCS

<h6>Taille: <span class="text-success">@Model.Grp.DATA_TAILLES.LIBELLE.Substring(0, 1).ToUpper()@Model.Grp.DATA_TAILLES.LIBELLE.Substring(1).ToLower()</span></h6>
<h6>Region: <span class="text-success">@Model.Grp.DATA_REGIONS.REGION</span></h6>
<h6>Secteur: <span class="text-success">@Model.Grp.DATA_SECTEURS.LIBELLE</span></h6>
<h6>Segment: <span class="text-success">@Model.Grp.DATA_SEGMENTS.LIBELLE.Substring(0, 1).ToUpper()@Model.Grp.DATA_SEGMENTS.LIBELLE.Substring(1).ToLower()</span> </h6>

SalesManagement/Views/Shared/_Layout.cshtml
<!DOOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sales Management</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/toastr.css")

    <link href="~/Content/design.css" rel="stylesheet" />
    <link href="~/DataTables/datatables.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Livvic|Merriweather&display=swap" rel="stylesheet">
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">

</head>
<body>
    <div class='wrapper'>
        <div class='sidebar'>
            <div class='title'>Sales Management</div>
            <ul class='main-nav nav'>
                @{var canDo = "Informations des "; }
                <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                <li>@Html.ActionLink(canDo + "liaisons entre les commerciaux et les groupes", "Index", "SalesGroups")</li>
                <li>@Html.ActionLink(canDo + "commerciaux", "Index", "Sales")</li>
                <li>@Html.ActionLink(canDo + "groupes", "Index", "Groups")</li>
                @if (User.IsInRole("GSA-ABW-SM-W"))
                {
                    <li>@Html.ActionLink("Lier un établissement à un groupe", "Index", "ETB")</li>
                }
                <li>@Html.ActionLink("Informations des établissements rattachés aux groupes", "Index", "GE")</li>
                <li>@Html.ActionLink("Aide", "Index", "Help")</li>

                <li><a class="glyphicon navbar-logout glyphicon-off" href="#" data-toggle="modal" data-target="#logoutModal"></a></li>
            </ul>
        </div>
        <div class="container body-content">
            <div class="body">
                @RenderBody()
                <div class="modal fade" id="logoutModal" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title"><i class="fa fa-toggle-off" aria-hidden="true"></i> Déconnexion</h4>
                            </div>
                            <div class="modal-body">
                                <p>Voulez-vous vous déconnecter ?</p>
                            </div>
                            <div class="modal-footer">
                                <a class="btn btn-default" href="Account/Logoff ">Oui</a>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Non</button>
                            </div>
                        </div>
                    </div>
                </div>
                <hr />
                <footer class="footer">

                    <p>&copy; @DateTime.Now.Year - Abilways</p>
                </footer>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js"></script>
    <script src="~/Scripts/jquery.smartWizard.js"></script>
    <script src="~/DataTables/datatables.js"></script>
    <script src="~/Scripts/jquery.signalR-2.4.1.js"></script>
    <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
    @Scripts.Render("~/signalr/hubs")

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    @RenderSection("scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>

</body>
</html>


<script>
    $(document).ready(function () {
        $('#createGroupModal').on('show.bs.modal', function (event) {
            $(".lbError").hide();

            var modal = $(this);

            modal.find('#libelleGrp').val("");

        });
        $('#deleteGE').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var etbid = button.data('etbid');
            var idgroupe = button.data('idgroupe');
            var modal = $(this);

            modal.find('#deleteGEetbid').val(etbid);
            modal.find('#deleteGEidgroupe').val(idgroupe);
        });

        $('#createGroupModalBtn').click(function () {
            $(".lbError").hide();

            $.ajax({
                url: '/Groups/AddGroup',
                success: function (data) {
                    $("#modal-bodyCreate").empty();
                    $("#modal-bodyCreate").append(data);
                    $("#modal-bodyCreate").append('<label class="text-danger col-lg-offset-1 lbError hidden" id="errorCreate"><i class="homepage-para-icon fa fa-warning" aria-hidden="true"></i>  Veuillez saisir tous les champs.</label>');
                    SetSegment();
                    GetSizeInfos($("#tailleGrp").val());
                }
            });
        });
        $(".lbError").hide();
    });
    function SetSegment() {

        var secteurForB2C = [99];
        var secteurForMedia = [13, 14];
        var secteurForSecteurPublic = [17, 18, 19, 20, 21, 22, 23];

        var secteurForIndustrie = [3, 5, 7, 8, 9, 10, 11, 16];
        var secteurForServices = [1, 2, 4, 6, 12, 15, 24, 25, 26];

        var GePmeMeEti = [1, 2, 3, 4];

        var secteur = parseInt($("#secteurGrp").val());
        var region = parseInt($("#regionGrp").val());
        var taille = parseInt($("#tailleGrp").val());

        if (region == 9 && contains.call(GePmeMeEti, taille) && (contains.call(secteurForIndustrie, secteur) || contains.call(secteurForServices, secteur))) { //Si la taille est une GePmeEti
            switch (true) {
                case contains.call(secteurForIndustrie, secteur): // Set Industrie
                    $("#selectSegment").val(3);
                    break;
                case contains.call(secteurForServices, secteur): // Set Service
                    $("#selectSegment").val(5);
                    break;
            }
        }
        switch (true) {
            case contains.call(secteurForB2C, secteur): // Set B2C
                $("#selectSegment").val(1);
                break;
            case contains.call(secteurForMedia, secteur): // Set Media
                $("#selectSegment").val(7);
                break;
            case contains.call(secteurForSecteurPublic, secteur): // Set secteur public
                $("#selectSegment").val(4);
                break;
            case contains.call(secteurForServices, secteur):
                $("#selectSegment").val(5);
                break;
            case contains.call(secteurForIndustrie, secteur):
                $("#selectSegment").val(3);
                break;
            default:
                $("#selectSegment").val(6);
        }
        var taille = parseInt($("#tailleGrp").val());
        var segment = parseInt($("#selectSegment").val());

        if (taille == 2 && (segment == 3 || segment == 5) && region != 9) {
            $("#selectSegment").val(2);
        }
        //$('#secteurGrp, #regionGrp, #tailleGrp, #selectSegment, #selectCom').selectpicker();
    }

    function CreateGroup() {
        var libelle = $("#libelleGrp").val();
        var idRegion = $("#regionGrp").val();
        var idTaille = $("#tailleGrp").val();
        var idSecteur = $("#secteurGrp").val();
        var idSegment = $("#selectSegment").val();
        var idCom = $("#selectCom").val();

        if (libelle != "") {
            $.ajax({
                url: "/Groups/CreateGroup?libelle=" + libelle + "&idRegion=" + idRegion + "&idTaille=" + idTaille + "&idSecteur=" + idSecteur + "&idSegment=" + idSegment + "&idCom=" + idCom,
                success: function (data) {
                    toastr.clear();
                    toastr.success("<br/>La création du groupe a été faite avec succès !", "ABILWAYS - Administration");
                    location.reload();
                }
            });
        }
        else {
            $("#errorCreate").show();
            $("#errorCreate").removeClass("hidden");
        }
    }

    function GetInfoGroup(idGroup) {
        $.ajax({
            url: '/Groups/GetInfosGroup?idGroup=' + idGroup + "&partialView=_InfosGroup_PartialView",
            success: function (data) {
                $("#infosGroup").empty();
                $("#infosGroup").html(data);
            }
        });
    }

    var contains = function (needle) {
        // Per spec, the way to identify NaN is that it is not equal to itself
        var findNaN = needle !== needle;
        var indexOf;

        if (!findNaN && typeof Array.prototype.indexOf === 'function') {
            indexOf = Array.prototype.indexOf;
        } else {
            indexOf = function (needle) {
                var i = -1, index = -1;

                for (i = 0; i < this.length; i++) {
                    var item = this[i];

                    if ((findNaN && item !== item) || item === needle) {
                        index = i;
                        break;
                    }
                }

                return index;
            };
        }

        return indexOf.call(this, needle) > -1;
    };

    function GetSizeInfos(idTaille) {
        $.ajax({
            url: "/Groups/GetSizeInfo?idTaille=" + idTaille,
            success: function (data) {
                $("#sizeInfo").empty();
                $("#sizeInfo").append(data);
            }
        })
    }
</script>

@if (!User.IsInRole("GSA-ABW-SM-W"))
{
    <script>
        $(document).ready(function () {
            $(".buttons-excel").hide();
        });
        $(document).ajaxStop(function () {
            $(".buttons-excel").hide();
        });
    </script>
}

<script>
    var url = $(location).attr('pathname');
    $(".main-nav > li > a").each(function (idx) {
        if ($(this).attr('href') == url) {
            $(this).addClass("bg-danger");
        }
    });
</script>

SalesManagement/Views/Shared/_SelectGroup_PartialView.cshtml
<select class="form-control " id="selectGroup" onchange="GetInfoGroup(this.value)" data-live-search="true">
    @foreach (var grp in Model)
    {
        <option value="@grp.IDGROUPE">@grp.LIBELLE</option>
    }
</select>